// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7kDekJ17LZ47ifXsmd1NcxLlJGBsvcow',
    appId: '1:780779534378:web:fb30fbf68f793b82b6ab53',
    messagingSenderId: '780779534378',
    projectId: 'jokes-app-flutter-4b91d',
    authDomain: 'jokes-app-flutter-4b91d.firebaseapp.com',
    storageBucket: 'jokes-app-flutter-4b91d.firebasestorage.app',
    measurementId: 'G-LXC7HTG7Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAevqJ5Z-7rYgCjuWufRqAmf4JyAi2i6D8',
    appId: '1:780779534378:android:5e3791a5a5891f52b6ab53',
    messagingSenderId: '780779534378',
    projectId: 'jokes-app-flutter-4b91d',
    storageBucket: 'jokes-app-flutter-4b91d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJrjeODohtNioONkl6vG-LJJtajfeFZpA',
    appId: '1:780779534378:ios:c813e4e64a4bc1f8b6ab53',
    messagingSenderId: '780779534378',
    projectId: 'jokes-app-flutter-4b91d',
    storageBucket: 'jokes-app-flutter-4b91d.firebasestorage.app',
    iosBundleId: 'com.example.jokesApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJrjeODohtNioONkl6vG-LJJtajfeFZpA',
    appId: '1:780779534378:ios:c813e4e64a4bc1f8b6ab53',
    messagingSenderId: '780779534378',
    projectId: 'jokes-app-flutter-4b91d',
    storageBucket: 'jokes-app-flutter-4b91d.firebasestorage.app',
    iosBundleId: 'com.example.jokesApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7kDekJ17LZ47ifXsmd1NcxLlJGBsvcow',
    appId: '1:780779534378:web:c01969e25597c375b6ab53',
    messagingSenderId: '780779534378',
    projectId: 'jokes-app-flutter-4b91d',
    authDomain: 'jokes-app-flutter-4b91d.firebaseapp.com',
    storageBucket: 'jokes-app-flutter-4b91d.firebasestorage.app',
    measurementId: 'G-R14D3T7TSK',
  );
}
